# -*- coding: utf-8 -*-
"""part1_grade_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHzNr5vFU0nieOSyaAW_66mXTMVI3emJ
"""

# Raw student data
students_data = [
    {"name": "  ayesha SHARMA ", "roll": "101", "marks_str": "88, 72, 95, 68, 78"},
    {"name": "ROHIT verma", "roll": "102", "marks_str": "55, 68, 49, 72, 61"},
    {"name": "   Priya Nair", "roll": "103", "marks_str": "91, 85, 88, 94, 79"},
    {"name": "karan MEHTA", "roll": "104", "marks_str": "40, 55, 38, 62, 50"},
    {"name": " sneha pillai ", "roll": "105", "marks_str": "75, 80, 70, 68, 85"}
]

clean_list = []

for s in students_data:

    # name clean karna
    clean_name = s["name"].strip().title()

    # roll convert
    roll_no = int(s["roll"])

    # marks list banana
    marks_list = []
    for m in s["marks_str"].split(","):
        marks_list.append(int(m))

    # name validation
    valid_flag = True
    for word in clean_name.split():
        if not word.isalpha():
            valid_flag = False

    # print output
    print("---------------")
    print("Student Name:", clean_name)
    print("Roll No:", roll_no)
    print("Marks:", marks_list)

    if valid_flag:
        print("Valid Name")
    else:
        print("Invalid Name")

    print("---------------\n")

    # store cleaned data
    clean_list.append({
        "name": clean_name,
        "roll": roll_no,
        "marks": marks_list
    })


# special case roll 103
for item in clean_list:
    if item["roll"] == 103:
        print("Special Output:")
        print(item["name"].upper())
        print(item["name"].lower())

# basic data
student_name = "Ayesha Sharma"

subjects = ["Math", "Physics", "CS", "English", "Chemistry"]
marks = [88, 72, 95, 60, 78]

print("Student:", student_name)
print("------------------------")

# loop for printing subject + grade
for i in range(len(subjects)):
    m = marks[i]

    if m >= 90:
        grade = "A+"
    elif m >= 80:
        grade = "A"
    elif m >= 70:
        grade = "B"
    elif m >= 60:
        grade = "C"
    else:
        grade = "F"

    print(subjects[i], ":", m, "-", grade)


# total marks
total = sum(marks)

# average
avg = total / len(marks)

print("\nTotal Marks:", total)
print("Average Marks:", round(avg, 2))


# highest
high_mark = max(marks)
high_index = marks.index(high_mark)
print("Highest:", subjects[high_index], "-", high_mark)

# lowest
low_mark = min(marks)
low_index = marks.index(low_mark)
print("Lowest:", subjects[low_index], "-", low_mark)


# ---- while loop part ----

count_new = 0

while True:
    sub = input("\nEnter subject name (or type done): ")

    if sub.lower() == "done":
        break

    m = input("Enter marks: ")

    # check valid number
    if not m.isdigit():
        print("Invalid input, skipping")
        continue

    m = int(m)

    if m < 0 or m > 100:
        print("Marks should be between 0-100")
        continue

    subjects.append(sub)
    marks.append(m)
    count_new += 1


# after loop
new_total = sum(marks)
new_avg = new_total / len(marks)

print("\nNew subjects added:", count_new)
print("Updated Average:", round(new_avg, 2))

# class data
class_student = [
    ("Ayesha Sharma", [88, 72, 95, 60, 78]),
    ("Rohit Verma", [55, 68, 49, 72, 61]),
    ("Priya Nair", [91, 85, 88, 94, 79]),
    ("Karan Mehta", [40, 55, 38, 62, 50]),
    ("Sneha Pillai", [75, 80, 70, 68, 85])
]

print("Name        | Avg   | Result")
print("-----------------------------")

pass_count = 0
fail_count = 0

all_avg = []

top_name = ""
top_avg = 0

# loop
for data in class_student:
    name = data[0]
    marks = data[1]

    total = sum(marks)
    avg = total / len(marks)

    avg = round(avg, 2)

    all_avg.append(avg)

    # result
    if avg >= 60:
        result = "Pass"
        pass_count += 1
    else:
        result = "Fail"
        fail_count += 1

    print(name, "|", avg, "|", result)

    # topper check
    if avg > top_avg:
        top_avg = avg
        top_name = name


# class average
class_avg = sum(all_avg) / len(all_avg)

print("\nPassed:", pass_count)
print("Failed:", fail_count)

print("Topper:", top_name, "-", round(top_avg, 2))
print("Class Average:", round(class_avg, 2))

# given essay
essay = " python is a versatile language. it supports object oriented, functional, and procedural programming. python is widely used in data science and machine learning. "

# step 1 - clean spaces
clean_essay = essay.strip()
print("Clean Essay:")
print(clean_essay)

# step 2 - title case
title_version = clean_essay.title()
print("\nTitle Case:")
print(title_version)

# step 3 - count 'python'
count_python = clean_essay.count("python")
print("\nCount of 'python':", count_python)

# step 4 - replace word
replaced = clean_essay.replace("python", "Python 🐍")
print("\nReplaced Version:")
print(replaced)

# step 5 - split sentences
sentences = clean_essay.split(". ")
print("\nSentences List:")
print(sentences)

# step 6 - print properly
print("\nFormatted Sentences:")
num = 1

for s in sentences:
    if s != "":
        if not s.endswith("."):
            s = s + "."

        print(str(num) + ".", s)
        num += 1